<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Tightenco\Ziggy\Ziggy;

class GenerateZiggy extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'ziggy:generate {--path=resources/js} {--group=web}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate Ziggy routes file';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $group = $this->option('group');
        $ziggy = new Ziggy($group);
        $path = $this->option('path');

        $this->info('Generating Ziggy routes for group: ' . $group);

        $content = '// This file is auto-generated by the GenerateZiggy command
export const Ziggy = ' . json_encode($ziggy->toArray()) . ';';

        File::put($path . '/ziggy.js', $content);

        $this->info('Ziggy routes generated successfully at ' . $path . '/ziggy.js');
    }
}

